### ISSUE TITLE
View Projects List

### ISSUE THREAD

**Issue by jeromeabel** [xpcatalyst/xpcatalyst#1]
## Description

- **As** a visitor
- **I want to** view a list of projects
- **So that I can** see what kinds of projects are available on the platform

## Acceptance criteria

- **Given** I am on the home page of the web app
- **When** I navigate to the "Projects" section
- **Then** I should see a list of all available projects with their basic details (title, description, and owner)

## Tasks

- [x] Create a `projects.json` file with sample project data
- [x] Fetch and display projects from the JSON file
- [x] Design the "Projects" section to display project details : ProjectCard component with shadcn/tailwind

![Image](https://github.com/xpcatalyst/xpcatalyst/assets/48929525/cb78c085-7e4f-402b-bc64-9996c59cc2ab)
