### ISSUE TITLE
Account Registration

### ISSUE THREAD

**Issue by jeromeabel** [xpcatalyst/xpcatalyst#10]
## User Story
- **As a visitor**,
- I want to register for an account using github, google or traditional methods, 
- so that I can easily create an account on the platform

## Acceptance Criteria
- Given I am a visitor on the registration page
- When I choose to register using GitHub, Google, or email/password
- Then I should be able to complete the registration process
- And I should be redirected to my account dashboard
- And I should see a welcome message confirming my successful registration

## Tasks
- [x] Set up Supabase
- [ ] Tests register component: rendering, form validation, utility functions
- [ ] Implement basic component, form validation, placeholder function for authentication methods
- [ ] Test integration : components, mock supabase
- [ ] Implement Supabase integration
- [ ] Tests e2e: complete registration flows, error scenarios, successful registration and redirection
- [ ] Implement register process, redirection to dashboard, welcome message after successful registration
- [ ] Optimize code, performance, error handling, user feedback
