### ISSUE TITLE
Search Projects

### ISSUE THREAD

**Issue by jeromeabel** [xpcatalyst/xpcatalyst#2]
## Description

- **As** a visitor
- **I want to** search for projects
- **So that I can** find specific projects of interest quickly

## Acceptance criteria

- **Given** I am on the "Projects" page
- **When** I enter a search term in the search bar
- **Then** I should see a list of projects that match the search term

## Tasks

- [x] Add a search bar to the "Projects" page
- [x] Implement search functionality to filter projects based on the search term using data from the JSON file
- [x] Update the projects list in real-time as the search term is entered
