### ISSUE TITLE
Sort Projects

### ISSUE THREAD

**Issue by jeromeabel** [xpcatalyst/xpcatalyst#4]
## Description

- **As** a visitor
- **I want to** sort projects by various criteria (e.g., most recent, most liked)
- **So that I can** view projects in a preferred order

## Acceptance criteria

- **Given** I am on the "Projects" page
- **When** I select a sorting option
- **Then** I should see the list of projects ordered according to the selected criteria

## Tasks

- [x] Add sorting options to the "Projects" page
- [x] Implement sorting functionality to order projects based on selected criteria using data from the JSON file
- [x] Ensure the projects list updates in real-time as sorting options are selected
